#!/bin/bash
# Copyright 2015 Navel-IT
# Navel Scheduler is developped by Yoann Le Garff, Nicolas Boquet and Yann Le Bras under GNU GPL v3
#
# chkconfig: - 98 02

#-> BEGIN

#-> initialization

. /etc/rc.d/init.d/functions

ECHO='echo'
TOUCH='touch'
RM='rm'

prog='navel-scheduler'

prog_full_path="/usr/local/bin/${prog}"

lockfile="/var/lock/subsys/${prog}.lock"
pidfile="/var/run/${prog}.pid"
sysconfig="/etc/sysconfig/${prog}"

[[ -r ${sysconfig} ]] && . ${sysconfig}

#-> functions

f_start() {
    ${ECHO} "Starting ${prog} ..."

    daemon --pidfile=${pidfile} ${prog_full_path} ${OPTS}

    ${TOUCH} ${lockfile}
}

f_stop() {
    ${ECHO} "Stopping ${prod} ..."

    killproc -p ${prog_full_path}

    ${RM} -f ${lockfile}
}

#-> main

case ${1} in
    start)
        f_start ;;
    stop)
        f_stop ;;
    status)
        status -p ${prog} ;;
    restart)
        f_stop

        f_start

        ;;
    *)
        ${ECHO} "Usage : $0 {start|stop|restart|status}"

        exit 1

        ;;
esac

#-> END